apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.stunner.auth.secretName }}
type: Opaque
stringData:
  type: {{ .Values.stunner.auth.type }}
  {{- if eq .Values.stunner.auth.type "ephemeral" }}
  secret: {{ required "auth.sharedSecret is required for ephemeral type" .Values.stunner.auth.sharedSecret }}
  {{- else if eq .Values.stunner.auth.type "static" }}
  username: {{ required "auth.username is required for static type" .Values.stunner.auth.username }}
  password: {{ required "auth.password is required for static type" .Values.stunner.auth.password }}
  {{- else }}
  {{- fail "Invalid auth.type - must be 'ephemeral' or 'static'" }}
  {{- end }}